# Generated by Django 3.2.7 on 2021-09-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_compt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_Number', models.IntegerField(null=True)),
                ('mails', models.EmailField(max_length=100)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('categorie_shop', models.CharField(max_length=50)),
                ('shop_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user_compt')),
            ],
        ),
        migrations.CreateModel(
            name='User_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_user', models.URLField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.user_compt')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50)),
                ('article_type', models.CharField(max_length=100)),
                ('article_description', models.TextField(max_length=255)),
                ('article_price', models.IntegerField()),
                ('article_quantity', models.IntegerField()),
                ('article_date', models.DateTimeField(auto_now_add=True)),
                ('article_available', models.BooleanField(default=True)),
                ('user_shop_id', models.ManyToManyField(to='store.User_shop')),
            ],
        ),
    ]
