# Generated by Django 3.2.7 on 2021-09-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='photo_user',
            field=models.ImageField(upload_to='image_profil/'),
        ),
    ]
