# Generated by Django 3.2.7 on 2021-09-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_profil_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
